### ISSUE TITLE
User stories: Freelancer

### ISSUE THREAD

**Issue by nataphilips** [nataphilips/tablesurfing#2]
- [ ] As a freelancer, I want to find a free office to work #4 
- [ ] I want to see each particular office profile #10 
- [ ] I want to be able to log in to the app #6
- [ ] I want to be able to contact a host #7
- [ ] I want to be able to decline an invitation #8
- [ ] I want to set up my profile #10
- [ ] I want to review and rank the offices I've been #11
