### ISSUE TITLE
User Stories: Host

### ISSUE THREAD

**Issue by nataphilips** [nataphilips/tablesurfing#3]
- [ ] As a host, I want to see the benefits of table sharing on the front page #9
- [ ] I want to be able to see the list of freelancers and invite them to my office #12
- [ ] I want to see each profile of available guests #13 
- [ ] I want to accept or decline an applicant #14
- [ ] I need to be signed in to use the website #6 
- [ ] I want to set up my profile #10
- [ ] I want to review and ranking mechanics #11
